Entity/EntityTypeNode.php
<?php

namespace Nodeart\BuilderBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use GraphAware\Neo4j\OGM\Annotations as OGM;
use Nodeart\BuilderBundle\Helpers\TemplateTwigFileResolver;

/**
 * @OGM\Node(label="EntityType", repository="Nodeart\BuilderBundle\Entity\Repositories\EntityTypeNodeRepository")
 */
class EntityTypeNode
{
    use isCommentableTrait;

    /**
     * @OGM\GraphId()
     * @var int
     */
    protected $id;

    /**
     * @OGM\Property(type="string")
     * @var string
     */
    protected $name;

    /**
     * @OGM\Property(type="string")
     * @var string
     */
    protected $slug = '';

    /**
     * @OGM\Property(type="string")
     * @var string
     */
    protected $description = '';

    /**
     * @OGM\Property(type="boolean")
     * @var boolean
     */
    protected $isDataType = false;

    /**
     * @OGM\Property(type="string")
     * @var string
     */
    protected $mainPictureField = '';

    /**
     * @OGM\Property(type="string", nullable=true)
     * @var string
     */
    protected $twigFilePath = null;

    /**
     * @OGM\Property(type="string", nullable=true)
     * @var string
     */
    protected $twigFilePathAsChild = null;

    /**
     * @OGM\Property(type="string", nullable=true)
     * @var string
     */
    protected $twigSingleObjectPath = null;

    /**
     * @OGM\Property(type="array", nullable=true)
     * @var array
     */
    protected $requiredParents = null;

    /**
     * @OGM\Relationship(type="has_type", direction="INCOMING", targetEntity="ObjectNode", collection=true)
     * @var ArrayCollection|ObjectNode[]
     */
    protected $objects;

    /**
     * @OGM\Relationship(type="has_field", direction="INCOMING", targetEntity="TypeFieldNode", collection=true, mappedBy="entityType")
     * @var ArrayCollection|TypeFieldNode[]
     */
    protected $entityTypeFields;

    /**
     * @OGM\Relationship(type="is_child_of", direction="INCOMING", targetEntity="EntityTypeNode", collection=true, mappedBy="parentTypes")
     * @OGM\OrderBy(property="name", order="ASC")
     * @var ArrayCollection|EntityTypeNode[]
     */
    protected $childTypes;

    /**
     * @OGM\Relationship(type="is_child_of", direction="OUTGOING", targetEntity="EntityTypeNode", collection=true, mappedBy="childTypes")
     * @var ArrayCollection|EntityTypeNode[]
     */
    protected $parentTypes;

    public function __construct($name = '', $description = null)
    {
        $this->name = $name;
        $this->description = $description;
        $this->objects = new ArrayCollection();
        $this->entityTypeFields = new ArrayCollection();
        $this->childTypes = new ArrayCollection();
        $this->parentTypes = new ArrayCollection();
    }

    public function __toString()
    {
        return (string)$this->getId();
    }

    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * @param string $name
     */
    public function setName(string $name)
    {
        $this->name = $name;
    }

    /**
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * @param string $description
     */
    public function setDescription(string $description)
    {
        $this->description = $description;
    }

    /**
     * @return ArrayCollection|ObjectNode[]
     */
    public function getObjects()
    {
        return $this->objects;
    }

    /**
     * @param ObjectNode|ArrayCollection $objects
     */
    public function setObjects($objects)
    {
        $this->objects = $objects;
    }

    /**
     * @return ArrayCollection|TypeFieldNode[]
     */
    public function getEntityTypeFields()
    {
        return $this->entityTypeFields;
    }

    /**
     * @param ArrayCollection|TypeFieldNode[] $entityTypeFields
     */
    public function setEntityTypeFields($entityTypeFields)
    {
        $this->entityTypeFields = $entityTypeFields;
    }

    /**
     * @return string
     */
    public function getSlug(): string
    {
        return $this->slug;
    }

    /**
     * @param string $slug
     */
    public function setSlug(string $slug)
    {
        $this->slug = $slug;
    }

    /**
     * @param EntityTypeNode $parentType
     */
    public function addParentType($parentType)
    {
        if (!$this->parentTypes->contains($parentType)) {
            $this->parentTypes->add($parentType);
        }
    }

    /**
     * @param EntityTypeNode $parentType
     */
    public function removeParentType($parentType)
    {
        $this->parentTypes->removeElement($parentType);
    }

    /**
     * @param TypeFieldNode $typeField
     */
    public function addEntityTypeField($typeField)
    {
        if (!$this->entityTypeFields->contains($typeField)) {
            $this->entityTypeFields->add($typeField);
        }
    }

    /**
     * @param TypeFieldNode $typeField
     */
    public function removeEntityTypeField($typeField)
    {
        $this->entityTypeFields->removeElement($typeField);
    }

    /**
     * @param bool $onlyDataTypes
     * @return ArrayCollection|EntityTypeNode[]
     */
    public function getFilteredChildTypes(bool $onlyDataTypes = false)
    {
        $res = iterator_to_array($this->getChildTypes());
        $res = array_filter($res, function (EntityTypeNode $entityType) use ($onlyDataTypes) {
            return $entityType->isDataType() === $onlyDataTypes;
        });
        return $res;
    }

    /**
     * @return EntityTypeNode[]|ArrayCollection
     */
    public function getChildTypes()
    {
        return $this->childTypes;
    }

    /**
     * @param EntityTypeNode[]|ArrayCollection $childTypes
     */
    public function setChildTypes($childTypes)
    {
        $this->childTypes = $childTypes;
    }

    /**
     * @return bool
     */
    public function isDataType(): ?bool
    {
        return $this->isDataType;
    }

    /**
     * @param bool $isDataType
     *
     * @return EntityTypeNode
     */
    public function setIsDataType(bool $isDataType): EntityTypeNode
    {
        $this->isDataType = $isDataType;

        return $this;
    }

    /**
     * @param bool $onlyDataTypes
     * @return ArrayCollection|EntityTypeNode[]
     */
    public function getFilteredParentTypes(bool $onlyDataTypes = false)
    {
        $res = iterator_to_array($this->getParentTypes());
        $res = array_filter($res, function (EntityTypeNode $entityType) use ($onlyDataTypes) {
            return $entityType->isDataType() === $onlyDataTypes;
        });
        return $res;
    }

    /**
     * @return ArrayCollection|EntityTypeNode[]
     */
    public function getParentTypes()
    {
        return $this->parentTypes;
    }

    /**
     * @param EntityTypeNode[]|ArrayCollection $parentTypes
     */
    public function setParentTypes($parentTypes)
    {
        $this->parentTypes = $parentTypes;
    }

    /**
     * @return string
     */
    public function getTwigFilePathAsChild()
    {
        return $this->twigFilePathAsChild;
    }

    /**
     * @param string $twigFilePathAsChild
     */
    public function setTwigFilePathAsChild($twigFilePathAsChild)
    {
        $this->twigFilePathAsChild = ($twigFilePathAsChild === TemplateTwigFileResolver::DEFAULT_TEMPLATE_FULL_NAME) ? null : $twigFilePathAsChild;
    }

    /**
     * @return string
     */
    public function getTwigFilePath()
    {
        return $this->twigFilePath;
    }

    /**
     * @param string $twigFilePath
     */
    public function setTwigFilePath($twigFilePath)
    {
        $this->twigFilePath = ($twigFilePath === TemplateTwigFileResolver::DEFAULT_TEMPLATE_FULL_NAME) ? null : $twigFilePath;
    }

    /**
     * @return string
     */
    public function getTwigSingleObjectPath()
    {
        return $this->twigSingleObjectPath;
    }

    /**
     * @param string $twigSingleObjectPath
     */
    public function setTwigSingleObjectPath($twigSingleObjectPath)
    {
        $this->twigSingleObjectPath = $twigSingleObjectPath;
    }

    /**
     * @return string
     */
    public function getMainPictureField(): ?string
    {
        return $this->mainPictureField;
    }

    /**
     * @param string $mainPictureField
     */
    public function setMainPictureField(?string $mainPictureField)
    {
        $this->mainPictureField = $mainPictureField;
    }

    /**
     * @return array
     */
    public function getRequiredParents(): ?array
    {
        return $this->requiredParents;
    }

    /**
     * @param array $requiredParents
     */
    public function setRequiredParents(?array $requiredParents)
    {
        $this->requiredParents = $requiredParents;
    }

}

Controller/DefaultController.php
<?php

namespace Nodeart\BuilderBundle\Controller;

use Doctrine\Common\Collections\ArrayCollection;
use Nodeart\BuilderBundle\Entity\FieldValueNode;
use Nodeart\BuilderBundle\Entity\ObjectNode;
use Nodeart\BuilderBundle\Entity\Repositories\FieldValueNodeRepository;
use Nodeart\BuilderBundle\Entity\Repositories\ObjectNodeRepository;
use Nodeart\BuilderBundle\Entity\Repositories\TypeFieldNodeRepository;
use Nodeart\BuilderBundle\Entity\TypeFieldNode;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Annotation\Route;

class DefaultController extends Controller
{
    /**
     * Ajax file deletion
     * @todo: make it role based
     *
     * @Route("/builder/fieldValue/{id}/delete/ajax", name="builder_delete_ajax_fv_file")
     * @param $id int
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function deleteFVFileAction(int $id)
    {
        $nm = $this->get('neo.app.manager');
        /** @var FieldValueNodeRepository $fvRepository */
        $fvRepository = $nm->getRepository(FieldValueNode::class);
        /** @var FieldValueNode $fieldValueNode */
        $fieldValueNode = $fvRepository->findOneById($id);
        if (is_null($fieldValueNode)) {
            return new JsonResponse(['status' => 'error', 'message' => 'Not found'], 404);
        }
        $nm->remove($fieldValueNode, true);
        $nm->flush();

        return new JsonResponse(['status' => 'success', 'message' => 'File node deleted']);
    }

    /**
     * Ajax file unlink
     * @todo: make it role based
     *
     * @Route("/builder/fieldValue/{id}/unlink/object/{objectId}/ajax", name="builder_unlink_ajax_fv_file")
     * @param $id int
     * @param int $objectId
     *
     * @return \Symfony\Component\HttpFoundation\Response
     * @throws \Exception
     */
    public function unlinkFiedlValueAction(int $id, int $objectId)
    {
        $nm = $this->get('neo.app.manager');
        /** @var FieldValueNodeRepository $fvRepository */
        $fvRepository = $nm->getRepository(FieldValueNode::class);
        /** @var ObjectNodeRepository $oRepository */
        $oRepository = $nm->getRepository(ObjectNode::class);

        /** @var FieldValueNode $fieldValueNode */
        $fieldValueNode = $fvRepository->findOneById($id);
        /** @var ObjectNode $object */
        $object = $oRepository->findOneById($objectId);
        if (is_null($fieldValueNode) || is_null($object)) {
            return new JsonResponse(['status' => 'error', 'message' => 'Not found'], 404);
        }

        if ($fieldValueNode->getObjects()->contains($object)) {
            $fieldValueNode->removeObject($object);
        }
        if ($object->getFieldVals()->contains($fieldValueNode)) {
            $object->removeFieldValue($fieldValueNode);
        }

        $nm->persist($object);
        $nm->persist($fieldValueNode);
        $nm->flush();

        return new JsonResponse(['status' => 'success', 'message' => 'File node unlinked']);
    }

    /**
     * Ajax file link & replace
     * @todo: make it role based
     *
     * @Route("/builder/fieldValue/{ids}/link/object/{objectId}/ajax/{typeId}", name="builder_link_ajax_fv_file", defaults={"typeId"=null})
     * @param $ids string
     * @param int $objectId
     * @param int|null $typeId
     *
     * @return \Symfony\Component\HttpFoundation\Response
     * @throws \Exception
     */
    public function linkReplaceFieldValuesAction(string $ids, int $objectId, int $typeId = null)
    {
        $nm = $this->get('neo.app.manager');
        /** @var FieldValueNodeRepository $fvRepository */
        $fvRepository = $nm->getRepository(FieldValueNode::class);
        /** @var ObjectNodeRepository $oRepository */
        $oRepository = $nm->getRepository(ObjectNode::class);
        /** @var TypeFieldNodeRepository $tfRepository */
        $tfRepository = $nm->getRepository(TypeFieldNode::class);

        $ids = explode('-', $ids);
        $ids = array_map('intval', $ids);
        /** @var ArrayCollection $fieldValueNodes */
        $fieldValueNodes = $fvRepository->findByIds($ids);

        /** @var ObjectNode $object */
        $object = $oRepository->findOneById($objectId);
        /** @var TypeFieldNode $typeField */
        $typeField = is_null($typeId) ? null : $tfRepository->findOneById($typeId);

        if (empty($fieldValueNodes) || is_null($object) || (!is_null($typeId) && is_null($typeField))) {
            return new JsonResponse(['status' => 'error', 'message' => 'Not found'], 404);
        }

        /** @var FieldValueNode $fieldValueNode */
        foreach ($fieldValueNodes as $fieldValueNode) {
            $fieldValueNode->addObject($object);
            if ($fieldValueNode->getTypeField() == null) {
                $fieldValueNode->setTypeField($typeField);
            }
            $nm->persist($fieldValueNode);
        }

        //replace currentFieldValue by new fieldValue
        if (!$typeField->isCollection()) {
            /** @var FieldValueNode $existedFieldValue */
            foreach ($fvRepository->findObjectValuesByType($object, $typeField) as $existedFieldValue) {
                $existedFieldValue->removeObject($object);
                $object->removeFieldValue($existedFieldValue);
            }
        }
        $nm->persist($object);
        $nm->flush();

        $this->addFlash('success', 'Файлы успешно свзязаны с обьектом');

        return new JsonResponse(['status' => 'success', 'message' => 'FieldValue nodes are linked',]);
    }

}

Resources/views/default/add.type.html.twig
{% extends '::crud_page.html.twig' %}

{% block content %}
    <div class="twelve wide column">
        <h3 class="ui header">{{ "Существующие типы объектов"|trans }}</h3>
        {% if rootNodeTypes|length == 0 %}
            <div class="ui middle">
                <span>{{ "Нет таких"|trans }}</span>
            </div>
        {% else %}
            {% from _self import recursiveCategory %}
            <div class="ui middle aligned recursive list">
                {% for node in rootNodeTypes %}
                    <div class="item">
                        <div class="content">
                            {{ block('node_buttons') }}
                            <div class="ui dividing header" id="{{ node.slug }}">{{ node.name }}</div>
                            {% if node.childTypes %}
                                {{ recursiveCategory(node) }}
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>
    <div class="twelve wide column">
        <h1 class="ui header">{{ "Создать тип объекта"|trans }}</h1>
        {{ form(form) }}
    </div>
{% endblock %}

{% macro recursiveCategory(node) %}
    {% import _self as self %}

    {% if node.childTypes|length %}
        {% set renderdedChilds = [] %}
        <div class="list">
            {% set childs = getChilds(node) %}
            {% set dataChilds = childs['data'] %}
            {% set rootChilds = childs['root'] %}
            {% if dataChilds is not empty %}
                <div class="ui fluid accordion">
                    <div class="title">
                        <i class="dropdown icon"></i>
                        {{ "Типы данных"|trans }}
                    </div>
                    <div class="content">
                        {% for child in dataChilds %}
                            {% if child.id not in renderdedChilds %}
                                <div class="item transition visible">
                                    <div class="fullwidth data-types content">
                                        <div>
                                            {% set node = child %}
                                            {{ block('node_buttons') }}
                                            <div class=" ui dividing sub header">{{ child.name }}</div>
                                        </div>
                                    </div>
                                </div>
                                {% set renderdedChilds = renderdedChilds|merge([child.id]) %}
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            {% endif %}
            {% if rootChilds is not empty %}
                <div class="ui fluid accordion">
                    <div class="title">
                        <i class="dropdown icon"></i>
                        {{ "Связанные типы"|trans }}
                    </div>
                    <div class="content">
                        {% for child in rootChilds %}
                            {% if child.id not in renderdedChilds %}
                                <div class="item">
                                    <div class="fullwidth root-types content">
                                        <div>
                                            {% set node = child %}
                                            <div class="small ui dividing header">{{ child.name }}</div>
                                        </div>
                                    </div>
                                </div>
                                {% set renderdedChilds = renderdedChilds|merge([child.id]) %}
                            {% endif %}
                        {% endfor %}
                        {% set renderdedChilds = [] %}
                    </div>
                </div>
            {% endif %}
        </div>
    {% endif %}
{% endmacro %}

{% block node_buttons %}
    <div class="child-left right floated ui icon buttons">
        {% if not node.isDataType %}
            <a class="tiny ui button"
               href="{{ path('vListObject',{'entityType': node.slug}) }}"
               title="{{ 'Список обьектов - фронт'|trans }}">
                <i class="external icon"></i></a>
        {% endif %}
        <a class="tiny ui button" href="{{ path('builder_edit_type',{'id':node.id}) }}"
           title="{{ 'Редактирование типа'|trans }}">
            <i class="edit icon"></i></a>
        <a class="tiny ui button" href="{{ path('builder_edit_type_fields',{'id':node.id}) }}"
           title="{{ "Поля типа"|trans }}">
            <i class="list icon"></i></a>
        <a class="tiny ui button" href="{{ path('builder_list_objects',{'id':node.id}) }}"
           title="{{ "Перейти к списку объектов этого типа"|trans }}">
            <i class="database icon"></i></a>
        <a class="tiny ui button" href="{{ path('builder_add_type_object',{'typeId':node.id}) }}"
           title="{{ "Добавить объект"|trans }}">
            <i class="icons">
                <i class="database icon"></i>
                <i class="corner add icon"></i>
            </i></a>
    </div>
{% endblock %}

    {% block javascripts %}
        {{ parent() }}
        <script>
            $(document).ready(function () {
                let parentsDropdown = $('.f-hasParents');
                let dd = $('.f-requiredParents');
                let $menu = dd.find('.menu');
                // onchange of parents dropdown clear and change possible values of required parent types dropdown
                parentsDropdown.dropdown('setting', 'onChange', function (value, text, $selectedItem) {
                    dd.dropdown('clear');
                    if ($selectedItem) {
                        let vals = $(this).dropdown('get value').split('|^');
                        let currentValsStruct = [];
                        // collect selected items
                        for (let val in vals) {
                            if (vals.hasOwnProperty(val)) {
                                let label = $(this).dropdown('get item', vals[val]).text();
                                currentValsStruct.push({'label': label, 'value': vals[val]});
                            }
                        }

                        // append new option to menu
                        for (let newItem in currentValsStruct) {
                            $menu.append(`<div class="item" data-value="${currentValsStruct[newItem].value}">${currentValsStruct[newItem].label}</div>`);
                        }
                        dd.dropdown('refresh');
                    }
                });
            });
        </script>
    {% endblock %}

Resources/views/default/ajax.empty.content.html.twig
{{ block ('content') }}

Resources/views/default/default.pager.html.twig
{# if its only page - do not show pager at all #}
{% if pager.last != 1 %}
    <div class="ui pagination menu">
        {% if pager.previous is defined and pager.first < pager.pagesInRange|first %}
            <a class="item"
               href="{{ path(masterRoute, currentPageParams|merge({page:1, perPage:pager.limit})) }}">
                <i class="angle double left icon"></i></a>
            <a class="previous_item item"
               href="{{ path(masterRoute, currentPageParams|merge({page:pager.previous, perPage:pager.limit})) }}">
                <i class="angle left icon"></i>
            </a>
            <div class="disabled item">...</div>
        {% endif %}
        {% for page in pager.pagesInRange %}
            {% if page == pager.current %}
                <span class="active item">{{ page }}</span>
            {% else %}
                <a class="item"
                   href="{{ path(masterRoute, currentPageParams|merge({page:page, perPage:pager.limit})) }}">{{ page }}</a>
            {% endif %}
        {% endfor %}
        {% if pager.next is defined and pager.last > pager.pagesInRange|last %}
            <div class="disabled item">...</div>
            <a class="next_item item"
               href="{{ path(masterRoute, currentPageParams|merge({page:pager.next, perPage:pager.limit})) }}">
                <i class="angle right icon"></i>
            </a>
            <a class="item"
               href="{{ path(masterRoute, currentPageParams|merge({page:pager.last, perPage:pager.limit})) }}"><i
                        class="angle double right icon"></i></a>
        {% endif %}
    </div>
{% endif %}

Resources/views/default/delete.type.fields.html.twig
{% extends '::crud_page.html.twig' %}

{% block content -%}
    <div class="twelve wide column">
        {{ block('crud_modal') }}
        <h1 class="ui header">
            <div class="content">{{ "Удалить объект и все его значения?"|trans ~ ' ' ~ entity.name }}
                <div class="red-colored sub header">Действие необратимо! Если значения присутствуют в другом обьекте,
                    они не будут удалены.
                </div>
            </div>
        </h1>
        {% do form.submit.setRendered %}
        {{ form_start(form) }}
        <a class="ui left floated button primary" href="{{ path('builder_add_types',{}) }}">{{ "Назад"|trans }}</a>
        <button class="ui left floated red button"
                href="{{ path('builder_add_types',{}) }}">{{ "Удалить"|trans }}</button>
        {{ form_rest(form) }}
        {{ form_end(form) }}
    </div>
{%- endblock %}

Resources/views/default/edit.type.html.twig
{% extends '::crud_page.html.twig' %}

{% block content %}
    <div class="twelve wide column">
        <h1 class="ui header">{{ "Редактирование типа объекта"|trans }}</h1>
        {{ form(form) }}
        <a class="ui left floated button primary" href="{{ path('builder_add_types') }}"
           title="{{ "Перейти к списку объектов этого типа"|trans }}">{{ 'Назад'|trans }}</a>
        <a class="ui left floated button" href="{{ path('builder_edit_type_fields', {'id':entityType.id}) }}"
           title="{{ "Перейти редактированию полей этого типа"|trans }}"><i
                    class="list icon"></i>{{ 'Редактирование полей'|trans }}</a>
        <a class="ui left floated button" href="{{ path('builder_list_objects', {'id':entityType.id}) }}"
           title="{{ "Перейти к списку объектов этого типа"|trans }}"><i
                    class="database icon"></i>{{ 'Список объектов'|trans }}</a>
        {{ form(delete_form) }}
    </div>
{% endblock %}


{% block javascripts %}
    {{ parent() }}
    <script>
        $(document).ready(function () {
            let parentsDropdown = $('.f-hasParents');
            let requiredsDropdown = $('.f-requiredParents');
            let $menu = requiredsDropdown.find('.menu');
            // onchange of parents dropdown clear and change possible values of required parent types dropdown
            parentsDropdown.dropdown('setting', 'onChange', function (value, text, $selectedItem) {
                requiredsDropdown.dropdown('clear');
                requiredsDropdown.dropdown('clear');
                if ($selectedItem) {
                    refreshReqiredItems();
                }
            });

            // actually works with screeching a bit
            function refreshReqiredItems() {
                $menu.empty();
                let vals = parentsDropdown.dropdown('get value').split('|^');
                let currentValsStruct = [];
                // collect selected items
                for (let val in vals) {
                    if (vals.hasOwnProperty(val)) {
                        let label = parentsDropdown.dropdown('get item', vals[val]);
                        if (label !== false) {
                            currentValsStruct.push({'label': label.text(), 'value': vals[val]});
                        }
                    }
                }

                // append new option to menu
                for (let newItem in currentValsStruct) {
                    $menu.append(`<div class="item" data-value="${currentValsStruct[newItem].value}">${currentValsStruct[newItem].label}</div>`);
                }
                requiredsDropdown.dropdown('refresh');
            }

            // whoosh!
            refreshReqiredItems();
            requiredsDropdown.dropdown('restore default value');
        });
    </script>
{% endblock %}

Resources/views/default/list.object.html.twig
{% extends '::crud_page.html.twig' %}

{% block content %}
    <div class="twelve wide column">
        {% if entity.dataType %}
            <h3 class="ui header">{{ "Существующие объекты типа для данных "|trans ~ ' "' ~ entity.name ~ '"' -}}</h3>
        {% else %}
            <h3 class="ui header">{{ "Существующие объекты типа"|trans ~ ' ' ~ entity.name }}</h3>
        {% endif %}
        {% if objects|length == 0 %}
            <div class="ui middle">
                <span>{{ "Нет таких"|trans }}</span>
            </div>
        {% else %}
            <div class="ui middle aligned recursive list">
                {{ block('object_list') }}
                {% set currentPageParams = masterParams|merge(pager.orderParams) %}
                {% include '@Builder/default/default.pager.html.twig' %}
            </div>
        {% endif %}
        <a class="ui left floated button primary"
           href="{{ path('builder_add_type_object', {'id':entity.id}) }}">{{ 'Создать обьект'|trans }}</a>
        <a class="ui left floated button"
           href="{{ path('builder_edit_type',{'id':entity}) }}"><i
                    class="edit icon"></i>{{ 'Ред.'|trans ~ ' ' ~ entity.name }}</a>
        <hr/>
        <a class="ui left floated button primary backward"
           href="{{ path('builder_add_types') }}">{{ 'Назад'|trans }}</a>
    </div>
{% endblock %}


{% block object_list %}
    {% if entity.dataType %}
        {% for pair in objects %}
            <div class="item">
                <div class="content">
                    {{ block('node_buttons_data_object') }}
                    <div class="ui dividing header">
                        {{ getMainFields(pair.object, false)|default('Обьект #'~pair.object.id) }}
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        {% for pair in objects %}
            <div class="item">
                <div class="content">
                    {{ block('node_buttons_object') }}
                    <div class="ui dividing header">
                        {{ pair.object.name }}
                    </div>
                </div>
            </div>
        {% endfor %}
    {% endif %}
{% endblock %}

{% block node_buttons_object %}
    <div class="child-left right floated ui icon buttons">
        <a class="tiny ui button"
           href="{{ path('vSingleObject',{'entityType': pair.object.entityType.slug, 'object':pair.object.slug}) }}"
           title="{{ 'Страница обьекта'|trans }}">
            <i class="external icon"></i></a>
        <a class="tiny ui button" href="{{ path('builder_edit_big_object',{'id': pair.object.id}) }}"
           title="{{ 'Редактировать'|trans }}">
            <i class="edit icon"></i></a>
        <a class="tiny ui button" href="{{ path('builder_delete_object',{'id':pair.object.id}) }}"
           title="{{ "Удалить обьект"|trans }}">
            <i class="remove circle icon"></i></a>
    </div>
{% endblock %}

{% block node_buttons_data_object %}
    <div class="child-left right floated ui icon buttons">
        <a class="tiny ui button" href="{{ path('builder_edit_object',{'id':pair.object.id}) }}"
           title="{{ 'Редактировать'|trans }}">
            <i class="edit icon"></i></a>
        <a class="tiny ui button" href="{{ path('builder_delete_object',{'id':pair.object.id}) }}"
           title="{{ "Удалить обьект"|trans }}">
            <i class="remove circle icon"></i></a>
    </div>
{% endblock %}